import { AutomationSpec } from './types';

interface NodeRedNode {
  id: string;
  type: string;
  name: string;
  [key: string]: unknown;
}

let _nodeCounter = 0;
function nodeId() {
  return `af${(++_nodeCounter).toString(16).padStart(8, '0')}`;
}

/**
 * Renders an AutomationSpec as a Node-RED importable flow JSON
 */
export function renderNodeRed(spec: AutomationSpec): string {
  _nodeCounter = 0;
  const { intent, triggers, conditions, actions } = spec;

  const nodes: NodeRedNode[] = [];

  // Tab node
  const tabId = nodeId();
  nodes.push({
    id: tabId,
    type: 'tab',
    name: intent.slice(0, 50),
    disabled: false,
    info: `Generated by AutomationForge\nAutomation: ${intent}`,
  });

  // Trigger nodes
  const triggerNodeIds: string[] = [];
  triggers.forEach((t, i) => {
    const id = nodeId();
    triggerNodeIds.push(id);
    if (t.type === 'time') {
      nodes.push({
        id,
        type: 'inject',
        name: `Timer: ${t.at || 'scheduled'}`,
        props: [{ p: 'payload' }, { p: 'topic', vt: 'str' }],
        repeat: '',
        crontab: (t.at || '08:00').replace(':', ' ') + ' * * *',
        once: false,
        onceDelay: 0,
        topic: '',
        payload: '',
        payloadType: 'date',
        x: 100,
        y: 100 + i * 100,
        z: tabId,
        wires: [],
      });
    } else if (t.type === 'state' || t.type === 'input') {
      nodes.push({
        id,
        type: 'inject',
        name: `Trigger: ${t.device || 'sensor'} ${t.event || 'change'}`,
        props: [{ p: 'payload', v: t.event || 'on', vt: 'str' }],
        repeat: '',
        crontab: '',
        once: false,
        topic: t.device || 'sensor/state',
        payload: t.event || 'on',
        payloadType: 'str',
        x: 100,
        y: 100 + i * 100,
        z: tabId,
        wires: [],
      });
    } else {
      nodes.push({
        id,
        type: 'inject',
        name: `Trigger ${i + 1}`,
        payload: '',
        payloadType: 'date',
        repeat: '',
        crontab: '',
        once: false,
        x: 100,
        y: 100 + i * 100,
        z: tabId,
        wires: [],
      });
    }
  });

  // Function node with conditions
  const funcId = nodeId();
  const conditionCode = conditions.length
    ? conditions
        .map((c) => {
          if (c.type === 'numeric_state')
            return `if (!(msg.payload ${c.operator || '>='} ${c.value || 0})) return null;`;
          if (c.type === 'state') return `if (msg.payload !== "${c.value || 'on'}") return null;`;
          return '// condition check';
        })
        .join('\n  ')
    : '// No extra conditions';

  nodes.push({
    id: funcId,
    type: 'function',
    name: 'Check Conditions',
    func: `// AutomationForge — ${intent}\n${conditionCode}\nreturn msg;`,
    outputs: 1,
    noerr: 0,
    initialize: '',
    finalize: '',
    x: 320,
    y: 140,
    z: tabId,
    wires: [],
  });

  // Action nodes
  const actionNodeIds: string[] = [];
  actions.forEach((a, i) => {
    const id = nodeId();
    actionNodeIds.push(id);
    if (a.type === 'turn_on' || a.type === 'turn_off') {
      const state = a.type === 'turn_on';
      nodes.push({
        id,
        type: 'http request',
        name: `${a.type}: ${a.target || 'device'}`,
        method: 'POST',
        ret: 'txt',
        paytoqs: 'ignore',
        url: `http://YOUR_HA_HOST:8123/api/services/switch/turn_${state ? 'on' : 'off'}`,
        tls: '',
        persist: false,
        proxy: '',
        authType: 'bearer',
        senderr: false,
        x: 540,
        y: 100 + i * 80,
        z: tabId,
        wires: [[]],
      });
    } else if (a.type === 'delay') {
      nodes.push({
        id,
        type: 'delay',
        name: `Delay ${a.duration || 5000}ms`,
        pauseType: 'delay',
        timeout: String(Math.floor((a.duration || 5000) / 1000)),
        timeoutUnits: 'seconds',
        rate: '1',
        nbRateUnits: '1',
        rateUnits: 'second',
        randomFirst: '1',
        randomLast: '5',
        randomUnits: 'seconds',
        drop: false,
        x: 540,
        y: 100 + i * 80,
        z: tabId,
        wires: [[]],
      });
    } else {
      nodes.push({
        id,
        type: 'debug',
        name: `Action: ${a.type}`,
        active: true,
        tosidebar: true,
        console: false,
        tostatus: false,
        complete: 'payload',
        targetType: 'msg',
        x: 540,
        y: 100 + i * 80,
        z: tabId,
        wires: [],
      });
    }
  });

  // Wire up: triggers → function → first action
  triggerNodeIds.forEach((tid) => {
    const node = nodes.find((n) => n.id === tid);
    if (node) node.wires = [[funcId]];
  });
  const funcNode = nodes.find((n) => n.id === funcId);
  if (funcNode && actionNodeIds.length) funcNode.wires = [actionNodeIds];

  return JSON.stringify(nodes, null, 2);
}
