import { AutomationSpec } from './types';

/**
 * Renders an AutomationSpec as Home Assistant automation YAML
 */
export function renderHA(spec: AutomationSpec): string {
  const { intent, devices, triggers, conditions, actions, safetyNotes } = spec;

  const safetyBlock = safetyNotes.length
    ? `# ⚠️  Safety Notes:\n${safetyNotes.map((n) => `#   ${n}`).join('\n')}\n#\n`
    : '';

  const triggerYaml = triggers
    .map((t) => {
      if (t.type === 'state') {
        const entityId = t.device
          ? devices.find((d) => d.name === t.device)?.haEntityId || `binary_sensor.${t.device?.toLowerCase().replace(/\s+/g, '_')}`
          : 'binary_sensor.your_sensor';
        return `  - platform: state
    entity_id: ${entityId}
    to: "${t.event || 'on'}"`;
      }
      if (t.type === 'time') {
        return `  - platform: time
    at: "${t.at || '08:00:00'}"`;
      }
      if (t.type === 'numeric_state') {
        const entityId = t.device
          ? `sensor.${t.device.toLowerCase().replace(/\s+/g, '_')}`
          : 'sensor.your_sensor';
        return `  - platform: numeric_state
    entity_id: ${entityId}
    above: ${t.value || 0}`;
      }
      return `  - platform: state
    entity_id: sensor.your_sensor
    to: "on"`;
    })
    .join('\n\n');

  const conditionYaml = conditions.length
    ? conditions
        .map((c) => {
          if (c.type === 'time') {
            return `  - condition: time
    after: "${c.value || '08:00:00'}"
    before: "22:00:00"`;
          }
          if (c.type === 'state') {
            return `  - condition: state
    entity_id: input_boolean.your_flag
    state: "${c.value || 'on'}"`;
          }
          if (c.type === 'numeric_state') {
            const entityId = c.device
              ? `sensor.${c.device.toLowerCase().replace(/\s+/g, '_')}`
              : 'sensor.your_sensor';
            return `  - condition: numeric_state
    entity_id: ${entityId}
    ${c.operator === '<=' ? 'below' : 'above'}: ${c.value || 0}`;
          }
          return `  - condition: template
    value_template: "{{ true }}"`;
        })
        .join('\n\n')
    : '';

  const actionYaml = actions
    .map((a) => {
      if (a.type === 'turn_on') {
        const entityId = a.target
          ? `light.${a.target.toLowerCase().replace(/\s+/g, '_')}`
          : 'light.your_light';
        return `  - service: homeassistant.turn_on
    target:
      entity_id: ${entityId}`;
      }
      if (a.type === 'turn_off') {
        const entityId = a.target
          ? `light.${a.target.toLowerCase().replace(/\s+/g, '_')}`
          : 'light.your_light';
        return `  - service: homeassistant.turn_off
    target:
      entity_id: ${entityId}`;
      }
      if (a.type === 'delay') {
        const secs = Math.floor((a.duration || 5000) / 1000);
        return `  - delay:
      seconds: ${secs}`;
      }
      if (a.type === 'notify') {
        return `  - service: notify.mobile_app
    data:
      title: "AutomationForge"
      message: "${a.message || 'Automation triggered'}"`;
      }
      return `  - service: homeassistant.turn_on
    target:
      entity_id: switch.your_device`;
    })
    .join('\n\n');

  const deviceComments = devices
    .map((d) => `#   - ${d.name} (${d.type})${d.haEntityId ? ` → ${d.haEntityId}` : ''}`)
    .join('\n');

  return `# AutomationForge — Generated Home Assistant Automation
# Automation: ${intent}
#
# Required devices:
${deviceComments}
#
${safetyBlock}# Deploy: Copy to your configuration.yaml or automations.yaml
# Then call: Developer Tools → YAML → Check Configuration → Restart

automation:
  - id: "automationforge_${intent.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '').slice(0, 40)}"
    alias: "${intent}"
    description: "Generated by AutomationForge"
    mode: single
    max_exceeded: silent

    trigger:
${triggerYaml || '      - platform: state\n        entity_id: binary_sensor.your_sensor\n        to: "on"'}
${
  conditionYaml
    ? `
    condition:
${conditionYaml}
`
    : ''
}
    action:
${actionYaml || '      - service: homeassistant.turn_on\n        target:\n          entity_id: switch.your_device'}
`;
}
